- name: "Infraestructura Base"
  hosts: all
  become: true
  gather_facts: yes
  roles:
    - role: common
      tags: [ 'ssh', 'docker', 'vpn' ]

- name: "Fail2ban"
  hosts: all
  become: true
  gather_facts: no
  roles:
    - role: fail2ban
      tags: [ 'fail2ban' ]
  

- name: "MISP"
  hosts: debian-whale
  become: yes
  gather_facts: no
  vars:
    misp_base_dir: "/opt/misp"
    misp_base_url: "https://{{ ansible_ip }}:8448" # FIX ME: No funciona con el DNS  de tailscale
  roles:
    - role: misp
      tags: [ 'misp' ]
  
# - name: "Wazuh manager y la tropa"
#   hosts: wazuh-manager
#   become: yes
#   roles:
#     - role: wazuh
#       tags: [ 'wazuh-manager' ]

- name: "Wazuh Agent"
  hosts: wazuh_agents
  become: yes
  gather_facts: no
  roles:
    - role: wazuh
      tags: [ 'wazuh-agent' ]

- name: "Audit"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: audit
      tags: [ 'audit' ]

- name: "Maintenance"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: maintenance
      tags: [ 'maintenance' ]

- name: "Monitoring tools"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: monitor
      tags: [ 'portainer', 'weavescope' ]


- name: "Crowdsec"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: crowdsec
      tags: [ 'crowdsec' ]


- name: "Traefik + Coraza"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: traefik
      tags: [ 'traefik' ]

- name: "n8n"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: n8n
      tags: [ 'n8n' ]

- name: "Juice-Shop"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: juice-shop
      tags: [ 'juice-shop' ]

- name: "AdGuard"
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: adguard
      tags: [ 'adguard' ]