- name: "Infraestructura Base"
  hosts: debian-whale
  become: true
  roles:
    - role: internal/common
      tags: [ 'common', 'ssh', 'f2b', 'docker', 'vpn', 'config', 'deploy' ]

- name: "MISP"
  hosts: debian-whale
  become: yes
  roles:
    - role: internal/misp
      tags: [ 'misp', 'config', 'deploy', 'check' ]
  
# - name: "Wazuh y la tropa"
#   hosts: debian-whale
#   become: yes
#   roles:
#     - role: wazuh
#       tags: [ 'wazuh-manager', 'config', 'deploy', 'check' ]

