- name: Crear directorio para la configuración de Portainer
  ansible.builtin.file:
    path: /opt/portainer
    state: directory
    mode: '0755'

- name: Copiar el template del Docker Compose de Portainer
  ansible.builtin.template:
    src: templates/dcompose-portainer.yml.j2
    dest: /opt/portainer/docker-compose.yml
    mode: '0644'

- name: Parar y eliminar contenedor previo si existe (opcional pero seguro)
  community.docker.docker_container:
    name: portainer
    state: absent
  ignore_errors: true # Si no existe, que no de error

- name: Levantar Portainer desde el Template
  community.docker.docker_compose_v2:
    project_src: /opt/portainer
    state: present
    wait: yes