---
- name: "1. Crear carpetas para los datos"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/wazuh_data          # Para los logs de Wazuh
    - /opt/wazuh_indexer_data  # Para la base de datos de Wazuh
    - /opt/misp_data           # Para MISP
    - /opt/soanar/soc          # AQUÍ vivirá el docker-compose.yml
  become: true

- name: "2. Enviar el diseño del Docker Compose"
  ansible.builtin.template:
    src: docker-compose.yml.j2          # El que tienes en tu PC
    dest: /opt/soanar/soc/docker-compose.yml  # Cómo se llamará en el server
    mode: '0644'
  become: true

- name: "3. Levantar los contenedores (V2)"
  community.docker.docker_compose_v2:
    project_src: "/opt/soanar/soc"  # Le decimos que busque el archivo en esa carpeta
    state: present
    timeout: 300
  become: true