- name: "MISP | Esperar a que el puerto HTTPS esté abierto"
  wait_for:
    port: "{{ misp_https_port }}" 
    delay: 10
    timeout: 300

- name: "MISP | Verificar respuesta de la interfaz web"
  uri:
    url: "{{ misp_base_url }}"
    validate_certs: no
    status_code: [200, 302]     # Aceptamos 302 porque MISP suele redirigir al login
  register: misp_web_status
  until: misp_web_status.status in [200, 302]
  retries: 20
  delay: 15

- name: "MISP | Reportar estado"
  debug:
    msg: "MISP está arriba en {{ misp_base_url }} respondiendo con código {{ misp_web_status.status }}"