---

- name: "MISP | Asegurar directorios de persistencia"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "{{ misp_base_dir }}"
    - "{{ misp_base_dir }}/mysql"
    - "{{ misp_base_dir }}/data"

- name: "MISP | Generar archivo de configuración .env"
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ misp_base_dir }}/.env"
    mode: '0600'

- name: "MISP | Generar Docker Compose"
  ansible.builtin.template:
    src: dcompose-misp.yml.j2
    dest: "{{ misp_base_dir }}/docker-compose.yml"
    mode: '0644'

- name: "MISP | Levantar Stack con Docker Compose"
  community.docker.docker_compose_v2:
    project_src: "{{ misp_base_dir }}"
    state: present
    pull: always  # Estándar: intentar bajar la última versión si no existe
    remove_orphans: yes # Limpia contenedores antiguos si cambias el nombre en el .yml