---
- name: "Asegurar que el directorio de datos para n8n existe"
  tags: n8n
  ansible.builtin.file:
    path: /opt/n8n
    state: directory
    mode: '0777'
  become: true

- name: "Desplegar n8n (Cerebro de Automatización)"
  tags: n8n
  community.docker.docker_container:
    name: n8n
    image: n8nio/n8n:latest
    restart_policy: always
    ports:
      - "5678:5678"
    volumes:
      - /opt/n8n:/home/node/.n8n
    env:
      N8N_LOG_LEVEL: info
      GENERIC_TIMEZONE: "Europe/Madrid"
      N8N_SECURE_COOKIE: "false"

    labels:
      traefik.enable: "true"
      traefik.http.routers.n8n.rule: "Host(`{{ ansible_dns }}`)"
      traefik.http.routers.n8n.entrypoints: "web"
      traefik.http.routers.n8n.middlewares: "whitelist-segura@file"

  become: true