- name: "Programar limpieza semanal de Docker (Prune)"
  cron:
    name: "Docker system prune"
    special_time: weekly
    job: "docker system prune -f --volumes"

- name: "Reiniciar Docker"
  service:
    name: docker
    state: restarted