---
# Este archivo coordina las tareas del sistema base
- name: "SSH"
  include_tasks: ssh.yml
  tags: [ 'ssh' ]

- name: "Docker"
  include_tasks: docker.yml
  tags: [ docker' ]

- name: "VPN: Tailscale"
  include_tasks: vpn.yml
  tags: [ 'vpn' ]
