---
- name: "Asegurar que el directorio de datos para n8n existe"
  ansible.builtin.file:
    path: /opt/n8n_data
    state: directory
    mode: '0777'
  become: true

- name: "Desplegar n8n (Cerebro de Automatización)"
  community.docker.docker_container:
    name: n8n
    image: n8nio/n8n:latest
    restart_policy: always
    ports:
      - "5678:5678"
    volumes:
      - /opt/n8n_data:/home/node/.n8n
    env:
      N8N_LOG_LEVEL: info
      GENERIC_TIMEZONE: "Europe/Madrid"
  become: true

- name: "Instalar dependencias para el Agente de Wazuh"
  ansible.builtin.apt:
    name: [gnupg, apt-transport-https, lsb-release]
    state: present
  become: true

- name: "Descargar e instalar el Agente de Wazuh"
  ansible.builtin.apt:
    deb: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.2-1_amd64.deb"
  become: true

- name: "Configurar ossec.conf desde template"
  ansible.builtin.template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: '0640'
  become: true
  notify: Reiniciar Wazuh Agent  # Esto asegura que se reinicie si el archivo cambia

- name: "Asegurar que el Agente de Wazuh está habilitado y arrancado"
  ansible.builtin.systemd:
    name: wazuh-agent
    state: started # Ahora sí, arrancamos con la config ya puesta
    enabled: yes
  become: true