---

- name: Crear el directorio del proyecto
  file:
    path: "/opt/juice-shop"
    state: directory
    mode: '0755'


- name: "Obtener API Key limpia"
  shell: |
    docker exec crowdsec cscli bouncers delete MyTraefikBouncer || true
    docker exec crowdsec cscli bouncers add MyTraefikBouncer -o raw
  register: bouncer_result

- name: "Asignar variable"
  set_fact:
    crowdsec_api_key: "{{ bouncer_result.stdout | trim }}"

- name: Copiar la plantilla del Docker Compose
  template:
    src: dcompose-juice-shop.j2
    dest: "/opt/juice-shop/docker-compose.yml"


- name: Limpiar contenedores antiguos de Juice Shop
  community.docker.docker_container:
    name: juice-shop
    state: absent

- name: Levantar el contenedor con Docker Compose
  community.docker.docker_compose_v2:
    project_src: "/opt/juice-shop"
    state: present
    recreate: always  
    remove_orphans: yes