

---
- name: "Crear directorios de trabajo"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/traefik
    - /opt/traefik/config
    - /var/log/traefik

- name: Asegurar que el archivo access.log existe
  file:
    path: "/var/log/traefik/access.log"
    state: touch
    mode: '0666'



- name: "Generar archivo docker-compose.yml desde Template"
  template:
    src: templates/dcompose-traefik.yml.j2
    dest: /opt/traefik/docker-compose.yml

- name: "Generar Configuración Dinámica (Middlewares)"
  template:
    src: templates/dynamic_conf.yml.j2
    dest: /opt/traefik/config/dynamic_conf.yml

- name: "Levantar Traefik"
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
    recreate: always

# --- AQUÍ SIGUEN TUS TAREAS DE CONFIGURACIÓN ---

- name: "Configurar Reglas del WAF (OWASP Core Rule Set)"
  tags: coraza
  ansible.builtin.template:
    src: coraza.conf.j2
    dest: /opt/coraza/config/default.conf
  become: true